FORMAT: 1A
HOST: http://avwx.rest/api

# AVWX

The AVWX REST API is a publically-available, open-source REST API for aviation weather.

The service organizes METAR and TAF reports into their individual elements and returns them in JSON, XML, or YAML format. It does a considderable amount of error correction so that your report is as clean and thorough as possible. It has additional services like providing station information, translating the report into English, and creating summary strings meant to be read or spoken.

## METAR [/metar/{location}{?format,options,onfail}]

METAR reports are surface observations for a particular airfield or other station location. There are two standard formats: International and North American. The parser works with both, but it is up to the developer to do the correct interpretation of the data. Use the 'Units' key for labling and conversions.

This endpoint currently uses the old response format. The format will switch on **April 1, 2019** to the new response format found at /api/preview/metar. If you need more time, use the endpoint at /api/legacy/metar which will last until **July 1, 2019**

+ Parameters
    + location (string) - ICAO station ident or coordinate pair
    + options (string) - Additional options to include (info, translate, summary, speech)
    + format (string) - Desired response format (default=json, xml, yaml)
    + onfail (string) - Error or use out-of-date cache when unable to fetch report (default=error, cache)

### Get METAR Report for Station [GET]

Get the METAR for a specific station by ICAO ident.

The example shown uses the new response format at /api/preview/metar

+ Parameters
    + location:`KJFK`
    + format: `json`
    + onfail: `cache`

+ Response 200 (application/json)

        {
            "altimeter": {
                "repr": "3022",
                "spoken": "three zero point two two",
                "value": 30.22
            },
            "clouds": [
                {
                    "altitude": 250,
                    "modifier": null,
                    "repr": "FEW250",
                    "type": "FEW"
                }
            ],
            "dewpoint": {
                "repr": "25",
                "spoken": "two five",
                "value": 25
            },
            "flight_rules": "VFR",
            "meta": {
                "timestamp": "Tue, 04 Sep 2018 01:01:47 GMT"
            },
            "other": [],
            "raw": "KJFK 040051Z 20007KT 10SM FEW250 26/25 A3022 RMK AO2 SLP231 T02560250",
            "remarks": "RMK AO2 SLP231 T02560250",
            "remarks_info": {
                "dewpoint_decimal": {
                    "repr": "25.0",
                    "spoken": "two five point zero",
                    "value": 25.0
                },
                "temperature_decimal": {
                    "repr": "25.6",
                    "spoken": "two five point six",
                    "value": 25.6
                }
            },
            "runway_visibility": [],
            "sanitized": "KJFK 040051Z 20007KT 10SM FEW250 26/25 A3022 RMK AO2 SLP231 T02560250",
            "station": "KJFK",
            "temperature": {
                "repr": "26",
                "spoken": "two six",
                "value": 26
            },
            "time": {
                "dt": "Tue, 04 Sep 2018 00:51:00 GMT",
                "repr": "040051Z"
            },
            "units": {
                "altimeter": "inHg",
                "altitude": "ft",
                "temperature": "C",
                "visibility": "sm",
                "wind_speed": "kt"
            },
            "visibility": {
                "repr": "10",
                "spoken": "one zero",
                "value": 10
            },
            "wind_direction": {
                "repr": "200",
                "spoken": "two zero zero",
                "value": 200
            },
            "wind_gust": null,
            "wind_speed": {
                "repr": "07",
                "spoken": "seven",
                "value": 7
            },
            "wind_variable_direction": []
        }

### Get METAR Report for Coordinates [GET]

Get the METAR for a coordinate pair (lat,lon). The API will return the station nearest to those coordinates. Include `info` in the options to get details about the selected station.

The example shown uses the new response format at /api/preview/metar

+ Parameters
    + location: `51.47,-0.4`
    + options: `info,speech`
    + format: `json`

+ Response 200 (application/json)

        {
            "altimeter": {
                "repr": "1020",
                "spoken": "one zero two zero",
                "value": 1020
            },
            "clouds": [],
            "dewpoint": {
                "repr": "12",
                "spoken": "one two",
                "value": 12
            },
            "flight_rules": "VFR",
            "info": {
                "city": "London",
                "country": "GBR",
                "elevation": 24.4,
                "iata": "LHR",
                "icao": "EGLL",
                "latitude": 51.47916667,
                "longitude": -0.450555556,
                "name": "Heathrow",
                "priority": 6,
                "state": "ENG"
            },
            "meta": {
                "cache-timestamp": "Tue, 04 Sep 2018 01:10:21 GMT",
                "timestamp": "Tue, 04 Sep 2018 01:11:47 GMT"
            },
            "other": [],
            "raw": "EGLL 040050Z AUTO 35004KT 320V030 9999 NCD 15/12 Q1020 NOSIG",
            "remarks": "NOSIG",
            "remarks_info": {
                "dewpoint_decimal": null,
                "temperature_decimal": null
            },
            "runway_visibility": [],
            "sanitized": "EGLL 040050Z AUTO 35004KT 320V030 9999 NCD 15/12 Q1020 NOSIG",
            "speech": "Winds three five zero (variable three two zero to zero three zero) at 4kt. Visibility one zero kilometers. Temperature one five degrees Celsius. Dew point one two degrees Celsius. Altimeter one zero two zero. Sky clear",
            "station": "EGLL",
            "temperature": {
                "repr": "15",
                "spoken": "one five",
                "value": 15
            },
            "time": {
                "dt": "Tue, 04 Sep 2018 00:50:00 GMT",
                "repr": "040050Z"
            },
            "units": {
                "altimeter": "hPa",
                "altitude": "ft",
                "temperature": "C",
                "visibility": "m",
                "wind_speed": "kt"
            },
            "visibility": {
                "repr": "9999",
                "spoken": "nine nine nine nine",
                "value": 9999
            },
            "wind_direction": {
                "repr": "350",
                "spoken": "three five zero",
                "value": 350
            },
            "wind_gust": null,
            "wind_speed": {
                "repr": "04",
                "spoken": "four",
                "value": 4
            },
            "wind_variable_direction": [
                {
                    "repr": "320",
                    "spoken": "three two zero",
                    "value": 320
                },
                {
                    "repr": "030",
                    "spoken": "zero three zero",
                    "value": 30
                }
            ]
        }

## Parse METAR [/metar/parse{?format,options,onfail}]

Parses a METAR report supplied by the user.

+ Parameters

    + options (string) - Additional options to include (info, translate, summary, speech)
    + format (string) - Desired response format (default=json, xml, yaml)

### Parse a Given METAR [POST]

Parse a user-supplied METAR included as the plain text body of the request.

+ Parameters

    + options: `translate` 
    + format: `json`

+ Request (text/plain)

        PHKO 181753Z 28004KT 6SM HZ SCT022 27/21 A3005 RMK AO2 SLP178 T02670206 10267 20239 53009

+ Response 200 (application/json)

        {
            "altimeter": {
                "repr": "3005",
                "spoken": "three zero point zero five",
                "value": 30.05
            },
            "clouds": [
                {
                    "altitude": 22,
                    "modifier": null,
                    "repr": "SCT022",
                    "type": "SCT"
                }
            ],
            "dewpoint": {
                "repr": "21",
                "spoken": "two one",
                "value": 21
            },
            "flight_rules": "VFR",
            "meta": {
                "timestamp": "Tue, 04 Sep 2018 01:18:22 GMT"
            },
            "other": [
                "HZ"
            ],
            "raw": "PHKO 181753Z 28004KT 6SM HZ SCT022 27/21 A3005 RMK AO2 SLP178 T02670206 10267 20239 53009",
            "remarks": "RMK AO2 SLP178 T02670206 10267 20239 53009",
            "remarks_info": {
                "dewpoint_decimal": {
                    "repr": "20.6",
                    "spoken": "two zero point six",
                    "value": 20.6
                },
                "temperature_decimal": {
                    "repr": "26.7",
                    "spoken": "two six point seven",
                    "value": 26.7
                }
            },
            "runway_visibility": [],
            "sanitized": "PHKO 181753Z 28004KT 6SM HZ SCT022 27/21 A3005 RMK AO2 SLP178 T02670206 10267 20239 53009",
            "station": "PHKO",
            "temperature": {
                "repr": "27",
                "spoken": "two seven",
                "value": 27
            },
            "time": {
                "dt": "Sat, 18 Aug 2018 17:53:00 GMT",
                "repr": "181753Z"
            },
            "translations": {
                "altimeter": "30.05 inHg (1018 hPa)",
                "clouds": "Scattered clouds at 2200ft - Reported AGL",
                "dewpoint": "21°C (70°F)",
                "other": "Haze",
                "remarks": {
                    "10267": "6-hour maximum temperature 26.7°C",
                    "20239": "6-hour minimum temperature 23.9°C",
                    "53009": "3-hour pressure difference: +/- 0.9 mb - Decreasing or steady, then increasing",
                    "AO2": "Automated with precipitation sensor",
                    "SLP178": "Sea level pressure: 1017.8 hPa",
                    "T02670206": "Temperature 26.7°C and dewpoint 20.6°C"
                },
                "temperature": "27°C (81°F)",
                "visibility": "6sm (9.7km)",
                "wind": "W-280 at 4kt"
            },
            "visibility": {
                "repr": "6",
                "spoken": "six",
                "value": 6
            },
            "wind_direction": {
                "repr": "280",
                "spoken": "two eight zero",
                "value": 280
            },
            "wind_gust": null,
            "wind_speed": {
                "repr": "04",
                "spoken": "four",
                "value": 4
            },
            "wind_variable_direction": []
        }

## TAF [/taf/{location}{?format,options,onfail}]

TAF reports are atmospheric conditions for an area within five nautical miles of a particular airfield or other station location. Unlike METAR which only has two standard formats, TAF reports vary considderably more based on their geography. For example, Oceania TAF reports include two unique keys: Temp-List and Alt-List.

This endpoint currently uses the old response format. The format will switch on **April 1, 2019** to the new response format found at /api/preview/taf. If you need more time, use the endpoint at /api/legacy/taf which will last until **July 1, 2019**

+ Parameters
    + location (string) - ICAO station ident or coordinate pair
    + options (string) - Additional options to include (info, translate, summary)
    + format (string) - Desired response format (default=json, xml, yaml)
    + onfail (string) - Error or use out-of-date cache when unable to fetch report (default=error, cache)

### Get TAF Report for Station [GET]

Get the TAF for a specific station by ICAO ident.

The example shown uses the new response format at /api/preview/taf

+ Parameters
    + location:`KJFK`
    + options: `summary`
    + format: `json`
    + onfail: `cache`

+ Response 200 (application/json)

        {
            "alts": null,
            "end_time": {
                "dt": "Wed, 05 Sep 2018 06:00:00 GMT",
                "repr": "0506"
            },
            "forecast": [
                {
                    "altimeter": "",
                    "clouds": [
                        {
                            "altitude": 40,
                            "modifier": null,
                            "repr": "FEW040",
                            "type": "FEW"
                        }
                    ],
                    "end_time": {
                        "dt": "Tue, 04 Sep 2018 01:00:00 GMT",
                        "repr": "0401"
                    },
                    "flight_rules": "VFR",
                    "icing": [],
                    "other": [],
                    "probability": null,
                    "raw": "0400/0506 18011KT P6SM FEW040",
                    "sanitized": "0400/0506 18011KT P6SM FEW040",
                    "start_time": {
                        "dt": "Tue, 04 Sep 2018 00:00:00 GMT",
                        "repr": "0400"
                    },
                    "summary": "Winds S-180 at 11kt, Vis greater than 6sm, Few clouds at 4000ft",
                    "turbulance": [],
                    "type": "FROM",
                    "visibility": {
                        "repr": "P6",
                        "spoken": "greater than six",
                        "value": null
                    },
                    "wind_direction": {
                        "repr": "180",
                        "spoken": "one eight zero",
                        "value": 180
                    },
                    "wind_gust": null,
                    "wind_shear": "",
                    "wind_speed": {
                        "repr": "11",
                        "spoken": "one one",
                        "value": 11
                    }
                },
                {
                    "altimeter": "",
                    "clouds": [
                        {
                            "altitude": 50,
                            "modifier": null,
                            "repr": "SCT050",
                            "type": "SCT"
                        }
                    ],
                    "end_time": {
                        "dt": "Tue, 04 Sep 2018 03:00:00 GMT",
                        "repr": "0403"
                    },
                    "flight_rules": "VFR",
                    "icing": [],
                    "other": [],
                    "probability": null,
                    "raw": "FM040100 21006KT P6SM SCT050",
                    "sanitized": "FM040100 21006KT P6SM SCT050",
                    "start_time": {
                        "dt": "Tue, 04 Sep 2018 01:00:00 GMT",
                        "repr": "0401"
                    },
                    "summary": "Winds SSW-210 at 6kt, Vis greater than 6sm, Scattered clouds at 5000ft",
                    "turbulance": [],
                    "type": "FROM",
                    "visibility": {
                        "repr": "P6",
                        "spoken": "greater than six",
                        "value": null
                    },
                    "wind_direction": {
                        "repr": "210",
                        "spoken": "two one zero",
                        "value": 210
                    },
                    "wind_gust": null,
                    "wind_shear": "",
                    "wind_speed": {
                        "repr": "06",
                        "spoken": "six",
                        "value": 6
                    }
                },
                {
                    "altimeter": "",
                    "clouds": [
                        {
                            "altitude": 250,
                            "modifier": null,
                            "repr": "SCT250",
                            "type": "SCT"
                        }
                    ],
                    "end_time": {
                        "dt": "Tue, 04 Sep 2018 13:00:00 GMT",
                        "repr": "0413"
                    },
                    "flight_rules": "VFR",
                    "icing": [],
                    "other": [],
                    "probability": null,
                    "raw": "FM040300 VRB05KT P6SM SCT250",
                    "sanitized": "FM040300 VRB05KT P6SM SCT250",
                    "start_time": {
                        "dt": "Tue, 04 Sep 2018 03:00:00 GMT",
                        "repr": "0403"
                    },
                    "summary": "Winds Variable at 5kt, Vis greater than 6sm, Scattered clouds at 25000ft",
                    "turbulance": [],
                    "type": "FROM",
                    "visibility": {
                        "repr": "P6",
                        "spoken": "greater than six",
                        "value": null
                    },
                    "wind_direction": {
                        "repr": "VRB",
                        "spoken": "variable",
                        "value": null
                    },
                    "wind_gust": null,
                    "wind_shear": "",
                    "wind_speed": {
                        "repr": "05",
                        "spoken": "five",
                        "value": 5
                    }
                },
                {
                    "altimeter": "",
                    "clouds": [
                        {
                            "altitude": 250,
                            "modifier": null,
                            "repr": "FEW250",
                            "type": "FEW"
                        }
                    ],
                    "end_time": {
                        "dt": "Tue, 04 Sep 2018 16:00:00 GMT",
                        "repr": "0416"
                    },
                    "flight_rules": "VFR",
                    "icing": [],
                    "other": [],
                    "probability": null,
                    "raw": "FM041300 33006KT P6SM FEW250",
                    "sanitized": "FM041300 33006KT P6SM FEW250",
                    "start_time": {
                        "dt": "Tue, 04 Sep 2018 13:00:00 GMT",
                        "repr": "0413"
                    },
                    "summary": "Winds NNW-330 at 6kt, Vis greater than 6sm, Few clouds at 25000ft",
                    "turbulance": [],
                    "type": "FROM",
                    "visibility": {
                        "repr": "P6",
                        "spoken": "greater than six",
                        "value": null
                    },
                    "wind_direction": {
                        "repr": "330",
                        "spoken": "three three zero",
                        "value": 330
                    },
                    "wind_gust": null,
                    "wind_shear": "",
                    "wind_speed": {
                        "repr": "06",
                        "spoken": "six",
                        "value": 6
                    }
                },
                {
                    "altimeter": "",
                    "clouds": [
                        {
                            "altitude": 40,
                            "modifier": null,
                            "repr": "FEW040",
                            "type": "FEW"
                        },
                        {
                            "altitude": 250,
                            "modifier": null,
                            "repr": "SCT250",
                            "type": "SCT"
                        }
                    ],
                    "end_time": {
                        "dt": "Tue, 04 Sep 2018 18:00:00 GMT",
                        "repr": "0418"
                    },
                    "flight_rules": "VFR",
                    "icing": [],
                    "other": [],
                    "probability": null,
                    "raw": "FM041600 VRB04KT P6SM FEW040 SCT250",
                    "sanitized": "FM041600 VRB04KT P6SM FEW040 SCT250",
                    "start_time": {
                        "dt": "Tue, 04 Sep 2018 16:00:00 GMT",
                        "repr": "0416"
                    },
                    "summary": "Winds Variable at 4kt, Vis greater than 6sm, Few clouds at 4000ft, Scattered clouds at 25000ft",
                    "turbulance": [],
                    "type": "FROM",
                    "visibility": {
                        "repr": "P6",
                        "spoken": "greater than six",
                        "value": null
                    },
                    "wind_direction": {
                        "repr": "VRB",
                        "spoken": "variable",
                        "value": null
                    },
                    "wind_gust": null,
                    "wind_shear": "",
                    "wind_speed": {
                        "repr": "04",
                        "spoken": "four",
                        "value": 4
                    }
                },
                {
                    "altimeter": "",
                    "clouds": [
                        {
                            "altitude": 50,
                            "modifier": null,
                            "repr": "SCT050",
                            "type": "SCT"
                        },
                        {
                            "altitude": 250,
                            "modifier": null,
                            "repr": "SCT250",
                            "type": "SCT"
                        }
                    ],
                    "end_time": {
                        "dt": "Tue, 04 Sep 2018 23:00:00 GMT",
                        "repr": "0423"
                    },
                    "flight_rules": "VFR",
                    "icing": [],
                    "other": [],
                    "probability": null,
                    "raw": "FM041800 19008KT P6SM SCT050 SCT250",
                    "sanitized": "FM041800 19008KT P6SM SCT050 SCT250",
                    "start_time": {
                        "dt": "Tue, 04 Sep 2018 18:00:00 GMT",
                        "repr": "0418"
                    },
                    "summary": "Winds S-190 at 8kt, Vis greater than 6sm, Scattered clouds at 5000ft, Scattered clouds at 25000ft",
                    "turbulance": [],
                    "type": "FROM",
                    "visibility": {
                        "repr": "P6",
                        "spoken": "greater than six",
                        "value": null
                    },
                    "wind_direction": {
                        "repr": "190",
                        "spoken": "one nine zero",
                        "value": 190
                    },
                    "wind_gust": null,
                    "wind_shear": "",
                    "wind_speed": {
                        "repr": "08",
                        "spoken": "eight",
                        "value": 8
                    }
                },
                {
                    "altimeter": "",
                    "clouds": [
                        {
                            "altitude": 50,
                            "modifier": null,
                            "repr": "FEW050",
                            "type": "FEW"
                        },
                        {
                            "altitude": 250,
                            "modifier": null,
                            "repr": "SCT250",
                            "type": "SCT"
                        }
                    ],
                    "end_time": {
                        "dt": "Wed, 05 Sep 2018 03:00:00 GMT",
                        "repr": "0503"
                    },
                    "flight_rules": "VFR",
                    "icing": [],
                    "other": [],
                    "probability": null,
                    "raw": "FM042300 16005KT P6SM FEW050 SCT250",
                    "sanitized": "FM042300 16005KT P6SM FEW050 SCT250",
                    "start_time": {
                        "dt": "Tue, 04 Sep 2018 23:00:00 GMT",
                        "repr": "0423"
                    },
                    "summary": "Winds SSE-160 at 5kt, Vis greater than 6sm, Few clouds at 5000ft, Scattered clouds at 25000ft",
                    "turbulance": [],
                    "type": "FROM",
                    "visibility": {
                        "repr": "P6",
                        "spoken": "greater than six",
                        "value": null
                    },
                    "wind_direction": {
                        "repr": "160",
                        "spoken": "one six zero",
                        "value": 160
                    },
                    "wind_gust": null,
                    "wind_shear": "",
                    "wind_speed": {
                        "repr": "05",
                        "spoken": "five",
                        "value": 5
                    }
                },
                {
                    "altimeter": "",
                    "clouds": [
                        {
                            "altitude": 250,
                            "modifier": null,
                            "repr": "SCT250",
                            "type": "SCT"
                        }
                    ],
                    "end_time": {
                        "dt": "Wed, 05 Sep 2018 06:00:00 GMT",
                        "repr": "0506"
                    },
                    "flight_rules": "VFR",
                    "icing": [],
                    "other": [],
                    "probability": null,
                    "raw": "FM050300 13004KT P6SM SCT250",
                    "sanitized": "FM050300 13004KT P6SM SCT250",
                    "start_time": {
                        "dt": "Wed, 05 Sep 2018 03:00:00 GMT",
                        "repr": "0503"
                    },
                    "summary": "Winds SE-130 at 4kt, Vis greater than 6sm, Scattered clouds at 25000ft",
                    "turbulance": [],
                    "type": "FROM",
                    "visibility": {
                        "repr": "P6",
                        "spoken": "greater than six",
                        "value": null
                    },
                    "wind_direction": {
                        "repr": "130",
                        "spoken": "one three zero",
                        "value": 130
                    },
                    "wind_gust": null,
                    "wind_shear": "",
                    "wind_speed": {
                        "repr": "04",
                        "spoken": "four",
                        "value": 4
                    }
                }
            ],
            "max_temp": "",
            "meta": {
                "cache-timestamp": "Tue, 04 Sep 2018 01:22:37 GMT",
                "timestamp": "Tue, 04 Sep 2018 01:24:30 GMT"
            },
            "min_temp": "",
            "raw": "KJFK 032323Z 0400/0506 18011KT P6SM FEW040 FM040100 21006KT P6SM SCT050 FM040300 VRB05KT P6SM SCT250 FM041300 33006KT P6SM FEW250 FM041600 VRB04KT P6SM FEW040 SCT250 FM041800 19008KT P6SM SCT050 SCT250 FM042300 16005KT P6SM FEW050 SCT250 FM050300 13004KT P6SM SCT250",
            "remarks": "",
            "start_time": {
                "dt": "Tue, 04 Sep 2018 00:00:00 GMT",
                "repr": "0400"
            },
            "station": "KJFK",
            "temps": null,
            "time": {
                "dt": "Mon, 03 Sep 2018 23:23:00 GMT",
                "repr": "032323Z"
            },
            "units": {
                "altimeter": "inHg",
                "altitude": "ft",
                "temperature": "C",
                "visibility": "sm",
                "wind_speed": "kt"
            }
        }

### Get TAF Report for Coordinates [GET]

Get the TAF for a coordinate pair (lat,lon). The API will return the station nearest to those coordinates. Include `info` in the options to get details about the selected station.

The example shown uses the new response format at /api/preview/taf

+ Parameters
    + location: `51.47,-0.4`
    + options: `info`
    + format: `json`

+ Response 200 (application/json)

        {
            "alts": null,
            "end_time": {
                "dt": "Wed, 05 Sep 2018 06:00:00 GMT",
                "repr": "0506"
            },
            "forecast": [
                {
                    "altimeter": "",
                    "clouds": [
                        {
                            "altitude": 45,
                            "modifier": null,
                            "repr": "FEW045",
                            "type": "FEW"
                        }
                    ],
                    "end_time": {
                        "dt": "Tue, 04 Sep 2018 02:00:00 GMT",
                        "repr": "0402"
                    },
                    "flight_rules": "VFR",
                    "icing": [],
                    "other": [],
                    "probability": null,
                    "raw": "0400/0506 01004KT 9999 FEW045",
                    "sanitized": "0400/0506 01004KT 9999 FEW045",
                    "start_time": {
                        "dt": "Tue, 04 Sep 2018 00:00:00 GMT",
                        "repr": "0400"
                    },
                    "turbulance": [],
                    "type": "FROM",
                    "visibility": {
                        "repr": "9999",
                        "spoken": "nine nine nine nine",
                        "value": 9999
                    },
                    "wind_direction": {
                        "repr": "010",
                        "spoken": "zero one zero",
                        "value": 10
                    },
                    "wind_gust": null,
                    "wind_shear": "",
                    "wind_speed": {
                        "repr": "04",
                        "spoken": "four",
                        "value": 4
                    }
                },
                {
                    "altimeter": "",
                    "clouds": [],
                    "end_time": {
                        "dt": "Tue, 04 Sep 2018 05:00:00 GMT",
                        "repr": "0405"
                    },
                    "flight_rules": "MVFR",
                    "icing": [],
                    "other": [],
                    "probability": null,
                    "raw": "BECMG 0402/0405 8000",
                    "sanitized": "BECMG 0402/0405 8000",
                    "start_time": {
                        "dt": "Tue, 04 Sep 2018 02:00:00 GMT",
                        "repr": "0402"
                    },
                    "turbulance": [],
                    "type": "BECMG",
                    "visibility": {
                        "repr": "8000",
                        "spoken": "eight zero zero zero",
                        "value": 8000
                    },
                    "wind_direction": null,
                    "wind_gust": null,
                    "wind_shear": "",
                    "wind_speed": null
                },
                {
                    "altimeter": "",
                    "clouds": [
                        {
                            "altitude": 6,
                            "modifier": null,
                            "repr": "BKN006",
                            "type": "BKN"
                        }
                    ],
                    "end_time": {
                        "dt": "Tue, 04 Sep 2018 08:00:00 GMT",
                        "repr": "0408"
                    },
                    "flight_rules": "IFR",
                    "icing": [],
                    "other": [],
                    "probability": {
                        "repr": "30",
                        "spoken": "three zero",
                        "value": 30
                    },
                    "raw": "PROB30 TEMPO 0404/0408 BKN006",
                    "sanitized": "PROB30 TEMPO 0404/0408 BKN006",
                    "start_time": {
                        "dt": "Tue, 04 Sep 2018 04:00:00 GMT",
                        "repr": "0404"
                    },
                    "turbulance": [],
                    "type": "TEMPO",
                    "visibility": null,
                    "wind_direction": null,
                    "wind_gust": null,
                    "wind_shear": "",
                    "wind_speed": null
                },
                {
                    "altimeter": "",
                    "clouds": [],
                    "end_time": {
                        "dt": "Wed, 05 Sep 2018 06:00:00 GMT",
                        "repr": "0506"
                    },
                    "flight_rules": "VFR",
                    "icing": [],
                    "other": [],
                    "probability": null,
                    "raw": "BECMG 0406/0409 9999",
                    "sanitized": "BECMG 0406/0409 9999",
                    "start_time": {
                        "dt": "Tue, 04 Sep 2018 06:00:00 GMT",
                        "repr": "0406"
                    },
                    "turbulance": [],
                    "type": "BECMG",
                    "visibility": {
                        "repr": "9999",
                        "spoken": "nine nine nine nine",
                        "value": 9999
                    },
                    "wind_direction": null,
                    "wind_gust": null,
                    "wind_shear": "",
                    "wind_speed": null
                },
                {
                    "altimeter": "",
                    "clouds": [
                        {
                            "altitude": 12,
                            "modifier": null,
                            "repr": "BKN012",
                            "type": "BKN"
                        }
                    ],
                    "end_time": {
                        "dt": "Wed, 05 Sep 2018 06:00:00 GMT",
                        "repr": "0506"
                    },
                    "flight_rules": "IFR",
                    "icing": [],
                    "other": [],
                    "probability": {
                        "repr": "40",
                        "spoken": "four zero",
                        "value": 40
                    },
                    "raw": "PROB40 TEMPO 0503/0506 BKN012",
                    "sanitized": "PROB40 TEMPO 0503/0506 BKN012",
                    "start_time": {
                        "dt": "Wed, 05 Sep 2018 03:00:00 GMT",
                        "repr": "0503"
                    },
                    "turbulance": [],
                    "type": "TEMPO",
                    "visibility": null,
                    "wind_direction": null,
                    "wind_gust": null,
                    "wind_shear": "",
                    "wind_speed": null
                }
            ],
            "info": {
                "city": "London",
                "country": "GBR",
                "elevation": 24.4,
                "iata": "LHR",
                "icao": "EGLL",
                "latitude": 51.47916667,
                "longitude": -0.450555556,
                "name": "Heathrow",
                "priority": 6,
                "state": "ENG"
            },
            "max_temp": "",
            "meta": {
                "cache-timestamp": "Tue, 04 Sep 2018 01:26:01 GMT",
                "timestamp": "Tue, 04 Sep 2018 01:26:01 GMT"
            },
            "min_temp": "",
            "raw": "EGLL 032253Z 0400/0506 01004KT 9999 FEW045 BECMG 0402/0405 8000 PROB30 TEMPO 0404/0408 BKN006 BECMG 0406/0409 9999 PROB40 TEMPO 0503/0506 BKN012",
            "remarks": "",
            "start_time": {
                "dt": "Tue, 04 Sep 2018 00:00:00 GMT",
                "repr": "0400"
            },
            "station": "EGLL",
            "temps": null,
            "time": {
                "dt": "Mon, 03 Sep 2018 22:53:00 GMT",
                "repr": "032253Z"
            },
            "units": {
                "altimeter": "hPa",
                "altitude": "ft",
                "temperature": "C",
                "visibility": "m",
                "wind_speed": "kt"
            }
        }

## Parse TAF [/taf/parse{?format,options,onfail}]

Parses a TAF report supplied by the user.

+ Parameters

    + options (string) - Additional options to include (info, translate, summary, speech)
    + format (string) - Desired response format (default=json, xml, yaml)

### Parse a Given TAF [POST]

Parse a user-supplied TAF included as the plain text body of the request.

+ Parameters

    + options: `translate`
    + format: `json`

+ Request (text/plain)

        PHKO 181735Z 1818/1918 VRB03KT P6SM FEW035 FM182000 20010KT P6SM FEW030 SCT060 FM190400 10007KT P6SM FEW030 BKN050 FM191200 VRB03KT P6SM SCT030

+ Response 200 (application/json)

        {
            "alts": null,
            "end_time": {
                "dt": "Sun, 19 Aug 2018 18:00:00 GMT",
                "repr": "1918"
            },
            "forecast": [
                {
                    "altimeter": "",
                    "clouds": [
                        {
                            "altitude": 35,
                            "modifier": null,
                            "repr": "FEW035",
                            "type": "FEW"
                        }
                    ],
                    "end_time": {
                        "dt": "Sat, 18 Aug 2018 20:00:00 GMT",
                        "repr": "1820"
                    },
                    "flight_rules": "VFR",
                    "icing": [],
                    "other": [],
                    "probability": null,
                    "raw": "1818/1918 VRB03KT P6SM FEW035",
                    "sanitized": "1818/1918 VRB03KT P6SM FEW035",
                    "start_time": {
                        "dt": "Sat, 18 Aug 2018 18:00:00 GMT",
                        "repr": "1818"
                    },
                    "turbulance": [],
                    "type": "FROM",
                    "visibility": {
                        "repr": "P6",
                        "spoken": "greater than six",
                        "value": null
                    },
                    "wind_direction": {
                        "repr": "VRB",
                        "spoken": "variable",
                        "value": null
                    },
                    "wind_gust": null,
                    "wind_shear": "",
                    "wind_speed": {
                        "repr": "03",
                        "spoken": "three",
                        "value": 3
                    }
                },
                {
                    "altimeter": "",
                    "clouds": [
                        {
                            "altitude": 30,
                            "modifier": null,
                            "repr": "FEW030",
                            "type": "FEW"
                        },
                        {
                            "altitude": 60,
                            "modifier": null,
                            "repr": "SCT060",
                            "type": "SCT"
                        }
                    ],
                    "end_time": {
                        "dt": "Sun, 19 Aug 2018 04:00:00 GMT",
                        "repr": "1904"
                    },
                    "flight_rules": "VFR",
                    "icing": [],
                    "other": [],
                    "probability": null,
                    "raw": "FM182000 20010KT P6SM FEW030 SCT060",
                    "sanitized": "FM182000 20010KT P6SM FEW030 SCT060",
                    "start_time": {
                        "dt": "Sat, 18 Aug 2018 20:00:00 GMT",
                        "repr": "1820"
                    },
                    "turbulance": [],
                    "type": "FROM",
                    "visibility": {
                        "repr": "P6",
                        "spoken": "greater than six",
                        "value": null
                    },
                    "wind_direction": {
                        "repr": "200",
                        "spoken": "two zero zero",
                        "value": 200
                    },
                    "wind_gust": null,
                    "wind_shear": "",
                    "wind_speed": {
                        "repr": "10",
                        "spoken": "one zero",
                        "value": 10
                    }
                },
                {
                    "altimeter": "",
                    "clouds": [
                        {
                            "altitude": 30,
                            "modifier": null,
                            "repr": "FEW030",
                            "type": "FEW"
                        },
                        {
                            "altitude": 50,
                            "modifier": null,
                            "repr": "BKN050",
                            "type": "BKN"
                        }
                    ],
                    "end_time": {
                        "dt": "Sun, 19 Aug 2018 12:00:00 GMT",
                        "repr": "1912"
                    },
                    "flight_rules": "VFR",
                    "icing": [],
                    "other": [],
                    "probability": null,
                    "raw": "FM190400 10007KT P6SM FEW030 BKN050",
                    "sanitized": "FM190400 10007KT P6SM FEW030 BKN050",
                    "start_time": {
                        "dt": "Sun, 19 Aug 2018 04:00:00 GMT",
                        "repr": "1904"
                    },
                    "turbulance": [],
                    "type": "FROM",
                    "visibility": {
                        "repr": "P6",
                        "spoken": "greater than six",
                        "value": null
                    },
                    "wind_direction": {
                        "repr": "100",
                        "spoken": "one zero zero",
                        "value": 100
                    },
                    "wind_gust": null,
                    "wind_shear": "",
                    "wind_speed": {
                        "repr": "07",
                        "spoken": "seven",
                        "value": 7
                    }
                },
                {
                    "altimeter": "",
                    "clouds": [
                        {
                            "altitude": 30,
                            "modifier": null,
                            "repr": "SCT030",
                            "type": "SCT"
                        }
                    ],
                    "end_time": {
                        "dt": "Sun, 19 Aug 2018 18:00:00 GMT",
                        "repr": "1918"
                    },
                    "flight_rules": "VFR",
                    "icing": [],
                    "other": [],
                    "probability": null,
                    "raw": "FM191200 VRB03KT P6SM SCT030",
                    "sanitized": "FM191200 VRB03KT P6SM SCT030",
                    "start_time": {
                        "dt": "Sun, 19 Aug 2018 12:00:00 GMT",
                        "repr": "1912"
                    },
                    "turbulance": [],
                    "type": "FROM",
                    "visibility": {
                        "repr": "P6",
                        "spoken": "greater than six",
                        "value": null
                    },
                    "wind_direction": {
                        "repr": "VRB",
                        "spoken": "variable",
                        "value": null
                    },
                    "wind_gust": null,
                    "wind_shear": "",
                    "wind_speed": {
                        "repr": "03",
                        "spoken": "three",
                        "value": 3
                    }
                }
            ],
            "max_temp": "",
            "meta": {
                "timestamp": "Tue, 04 Sep 2018 01:27:49 GMT"
            },
            "min_temp": "",
            "raw": "PHKO 181735Z 1818/1918 VRB03KT P6SM FEW035 FM182000 20010KT P6SM FEW030 SCT060 FM190400 10007KT P6SM FEW030 BKN050 FM191200 VRB03KT P6SM SCT030",
            "remarks": "",
            "start_time": {
                "dt": "Sat, 18 Aug 2018 18:00:00 GMT",
                "repr": "1818"
            },
            "station": "PHKO",
            "temps": null,
            "time": {
                "dt": "Sat, 18 Aug 2018 17:35:00 GMT",
                "repr": "181735Z"
            },
            "translations": {
                "forecast": [
                    {
                        "altimeter": "",
                        "clouds": "Few clouds at 3500ft - Reported AGL",
                        "icing": "",
                        "other": "",
                        "turbulance": "",
                        "visibility": "Greater than 6sm ( >10km )",
                        "wind": "Variable at 3kt",
                        "wind_shear": ""
                    },
                    {
                        "altimeter": "",
                        "clouds": "Few clouds at 3000ft, Scattered clouds at 6000ft - Reported AGL",
                        "icing": "",
                        "other": "",
                        "turbulance": "",
                        "visibility": "Greater than 6sm ( >10km )",
                        "wind": "SSW-200 at 10kt",
                        "wind_shear": ""
                    },
                    {
                        "altimeter": "",
                        "clouds": "Few clouds at 3000ft, Broken layer at 5000ft - Reported AGL",
                        "icing": "",
                        "other": "",
                        "turbulance": "",
                        "visibility": "Greater than 6sm ( >10km )",
                        "wind": "E-100 at 7kt",
                        "wind_shear": ""
                    },
                    {
                        "altimeter": "",
                        "clouds": "Scattered clouds at 3000ft - Reported AGL",
                        "icing": "",
                        "other": "",
                        "turbulance": "",
                        "visibility": "Greater than 6sm ( >10km )",
                        "wind": "Variable at 3kt",
                        "wind_shear": ""
                    }
                ],
                "max_temp": "",
                "min_temp": "",
                "remarks": {}
            }
        }

## Multi-Station Request [/multi/{report_type}/{locations}{?format,options,onfail}]

This endpoint requires a paid API token and returns the results for multiple stations for a given report type ("metar", "taf"). It accepts the same request parameters as normal METAR and TAF requests, but accepts a comma-separated string of up to 10 stations in one call.

### Get METAR Reports [GET]

Shows a request for KJFK and KSFO in a single API call.

+ Parameters
    + report_type:`metar`
    + locations:`KJFK,KSFO`

+ Request
    + Headers
    
            Authorization: Token my_secret_api_token

+ Response 200 (application/json)

        {
            "KJFK": {
                "meta": {
                    "timestamp": "Tue, 22 Jan 2019 05:16:57 GMT",
                    "cache-timestamp": "Tue, 22 Jan 2019 05:15:20 GMT"
                },
                "altimeter": {
                    "repr": "3041",
                    "value": 30.41,
                    "spoken": "three zero point four one"
                },
                "clouds": [
                    {
                        "repr": "FEW045",
                        "type": "FEW",
                        "altitude": 45,
                        "modifier": null,
                        "direction": null
                    }
                ],
                "flight_rules": "VFR",
                "other": [],
                "sanitized": "KJFK 220451Z 30023G29KT 10SM FEW045 M10/M18 A3041 RMK AO2 PK WND 29029/0446 SLP296 T11001178 410941150",
                "visibility": {
                    "repr": "10",
                    "value": 10,
                    "spoken": "one zero"
                },
                "wind_direction": {
                    "repr": "300",
                    "value": 300,
                    "spoken": "three zero zero"
                },
                "wind_gust": {
                    "repr": "29",
                    "value": 29,
                    "spoken": "two nine"
                },
                "wind_speed": {
                    "repr": "23",
                    "value": 23,
                    "spoken": "two three"
                },
                "raw": "KJFK 220451Z 30023G29KT 10SM FEW045 M10/M18 A3041 RMK AO2 PK WND 29029/0446 SLP296 T11001178 410941150",
                "remarks": "RMK AO2 PK WND 29029/0446 SLP296 T11001178 410941150",
                "station": "KJFK",
                "time": {
                    "repr": "220451Z",
                    "dt": "Tue, 22 Jan 2019 04:51:00 GMT"
                },
                "dewpoint": {
                    "repr": "M18",
                    "value": -18,
                    "spoken": "minus one eight"
                },
                "remarks_info": {
                    "dewpoint_decimal": {
                        "repr": "-17.8",
                        "value": -17.8,
                        "spoken": "minus one seven point eight"
                    },
                    "temperature_decimal": {
                        "repr": "-10.0",
                        "value": -10.0,
                        "spoken": "minus one zero point zero"
                    }
                },
                "runway_visibility": [],
                "temperature": {
                    "repr": "M10",
                    "value": -10,
                    "spoken": "minus one zero"
                },
                "wind_variable_direction": [],
                "units": {
                    "altimeter": "inHg",
                    "altitude": "ft",
                    "temperature": "C",
                    "visibility": "sm",
                    "wind_speed": "kt"
                }
            },
            "KSFO": {
                "meta": {
                    "timestamp": "Tue, 22 Jan 2019 05:16:57 GMT",
                    "cache-timestamp": "Tue, 22 Jan 2019 05:15:32 GMT"
                },
                "altimeter": {
                    "repr": "3030",
                    "value": 30.3,
                    "spoken": "three zero point three"
                },
                "clouds": [
                    {
                        "repr": "FEW028",
                        "type": "FEW",
                        "altitude": 28,
                        "modifier": null,
                        "direction": null
                    }
                ],
                "flight_rules": "VFR",
                "other": [],
                "sanitized": "KSFO 220456Z 30007KT 10SM FEW028 12/06 A3030 RMK AO2 SLP262 T01220061 $",
                "visibility": {
                    "repr": "10",
                    "value": 10,
                    "spoken": "one zero"
                },
                "wind_direction": {
                    "repr": "300",
                    "value": 300,
                    "spoken": "three zero zero"
                },
                "wind_gust": null,
                "wind_speed": {
                    "repr": "07",
                    "value": 7,
                    "spoken": "seven"
                },
                "raw": "KSFO 220456Z 30007KT 10SM FEW028 12/06 A3030 RMK AO2 SLP262 T01220061 $",
                "remarks": "RMK AO2 SLP262 T01220061 $",
                "station": "KSFO",
                "time": {
                    "repr": "220456Z",
                    "dt": "Tue, 22 Jan 2019 04:56:00 GMT"
                },
                "dewpoint": {
                    "repr": "06",
                    "value": 6,
                    "spoken": "six"
                },
                "remarks_info": {
                    "dewpoint_decimal": {
                        "repr": "6.1",
                        "value": 6.1,
                        "spoken": "six point one"
                    },
                    "temperature_decimal": {
                        "repr": "12.2",
                        "value": 12.2,
                        "spoken": "one two point two"
                    }
                },
                "runway_visibility": [],
                "temperature": {
                    "repr": "12",
                    "value": 12,
                    "spoken": "one two"
                },
                "wind_variable_direction": [],
                "units": {
                    "altimeter": "inHg",
                    "altitude": "ft",
                    "temperature": "C",
                    "visibility": "sm",
                    "wind_speed": "kt"
                }
            }
        }