# Start from the official Python 3.6 container
FROM python:3.6.2

# Expose the default Flask port
EXPOSE 8000

# Set the main working directory
WORKDIR /home/avwx

# Set the service credentials as environment variables
# the host 'avwx-mongo' comes from the docker-compose.yaml 
ENV MONGO_URI='mongodb://avwx-mongo:27017'

# If you are not deploying using Docker, set the host of your own mongoDB
# ENV MONGO_URI='mongodb://cache:password==@loc.test.com:12345'

# http://www.geonames.org/login
ENV GN_USER='geonames-username'
ENV CLIENT_ACCESS_TOKEN='dialogflow client key'

# Go to your dashboard to get an agent API key https://console.dialogflow.com/api-client/
ENV CLIENT_ACCESS_TOKEN='dialog flow api key'

# Install the require Python packages
COPY requirements.txt /home/avwx/requirements.txt
RUN pip install -Ur requirements.txt
RUN pip install -U gunicorn

# Copy the application code
COPY avwx_api /home/avwx/avwx_api
COPY gunicorn_config.py /home/avwx/gunicorn_config.py

# Run the application
CMD ["gunicorn", "avwx_api:app", "-c", "gunicorn_config.py"]